---
title: ''
output: pdf_document
---

# Appendix: code

Analyses were conducted using the R Statistical language (version 4.2.1;
R Core Team, 2021) on Windows 11 x64. Code is available at
_<https://github.com/Minh-AnhHuynh/Osteosarcoma-Project>_.

<!-- Code philosophy follows ["The tidyverse style guide" written by Hadley -->
<!-- Wickham.](https://style.tidyverse.org/) and usage of tidyverse -->
<!-- functions, in order to ensure consistent code readability, usage and -->
<!-- naming. -->



\spacing{1}

<!-- TODO :  explain how data was created and imported (aka copy import script)-->


<!-- Appendix: All code for this report -->
 <!-- ```{r ref.label=knitr::all_labels(), echo=TRUE, eval=FALSE} -->
 <!-- ``` -->



```{r show-code, echo=TRUE, eval=FALSE}
<<signature_construction>>
# <<hp_osteosarcoma>>
# <<mcp_counter>>
# <<survival_code>>
# <<load_deseq2>>
# <<generate_raw_count>>
# <<deseq2>>
<<gsea>>
```

```{r echo=FALSE}
librarian::shelf(sessioninfo, quiet = TRUE)
sessioninfo::session_info("attached")
```

```{r echo=FALSE, results="asis"}
librarian::shelf(sessioninfo, quiet = TRUE)
pkgs <- sessioninfo::package_info("attached", dependencies = FALSE)
df <- tibble::tibble(
  Package = pkgs$package,
  Version = pkgs$ondiskversion,
  Source = gsub("@", "\\\\@", pkgs$source)
)
knitr::kable(df, format = "markdown")
```
